### PR TITLE
Add notebook on contextual optimization.

### PR DESCRIPTION
**Pull request by cqc-alec**
Follow-up to #59 (illustrating with a practical example but referring to the manual for details).

### CODE REVIEW

**Review by willsimmons1465 — COMMENTED** [review]
The notebook is fine. Could you commit a version with all of the cells run so that the outputs show up when viewed on GitHub?

**Comment by cqc-alec** [comment]
We've recently changed how we generate these notebooks -- the notebook itself is autogenerated from the python script. This is to make editing and source tracking easier. (The CI actually checks that it's correctly generated, so it can't be edited independently.)
This does mean that outputs aren't visible on github -- you have to run the notebook yourself to see them. (If we ran the notebook before committing it would contain a lot of environment-specific metadata.)

**Review by willsimmons1465 — APPROVED** [review]
Hmmm... Not sure if I agree with that decision as the vast amount of time when I look up notebooks in other software I just view it in GitHub, especially when I don't want to download software until I know what it does. But that discussion is separate from this PR and if it was already decided with good reason then I'll just shut up

**Comment by cqc-alec** [comment]
> Hmmm... Not sure if I agree with that decision as the vast amount of time when I look up notebooks in other software I just view it in GitHub, especially when I don't want to download software until I know what it does. But that discussion is separate from this PR and if it was already decided with good reason then I'll just shut up

You make a good point. I always thought of the notebooks as something to run to familiarize yourself with the software after installing it, but there may be a case for checking in outputs (even though they'll vary from run to run). Will give this some more thought.

**Pull request merged**
