### PR TITLE
Release/1.13.0

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Comment by cqc-melf** [comment]
I have an issues when building with the exception handling in the jupyter execute env, I have solved this now in https://github.com/CQCL/pytket/pull/223/commits/9b0e6871690a1be6a483fad8a02a6801512b7deb but this should be solved in a different way in the long term. I will create a issue for that.

**Comment by cqc-melf** [comment]
` +=` for qiskit circuits is not working any more, tried to solve this in https://github.com/CQCL/pytket/pull/223/commits/bfcc95bb3acf7aee575809d326b3264af6d642d6

**Review by cqc-alec — DISMISSED** [review]
Worth checking the logs to see what versions of sphinx etc are running and comparing with the last successful run to see what might be causing the error.

**Comment by cqc-alec** [comment]
Ah no, this is a real bug in pytket, the following code causes an abort:

```
In [1]: from pytket import Circuit, Qubit, Bit
   ...: 
   ...: circ = Circuit()
   ...: # set up a circuit with qubit a[0]
   ...: circ.add_qubit(Qubit("a", 0))

In [2]: circ.add_bit(Bit("a", 1))
[2023-03-17 13:23:48] [tket] [critical] Assertion '!reg_info || (reg_info.value() == correct_info)' (/root/.conan/data/tket/1.0.55/tket/stable/build/b3fe2dd8cea3a35f00ed1eabd660e74f6798b3fd/Circuit/basic_circ_manip.cpp : add_bit : 428) failed.  Aborting.
Aborted (core dumped)
```

**Comment by cqc-alec** [comment]
https://github.com/CQCL/tket/issues/790

**Comment by cqc-melf** [comment]
Should be working now

**Review by cqc-alec — APPROVED** [review]

**Pull request merged**
