### PR TITLE
Release/1.3.0

### PR DESCRIPTION
**Pull request by cqc-melf**
update pytket to 1.3 and update extensions corresponding

### CODE REVIEW

**Comment by cqc-melf** [comment]
@cqc-alec this looks like a issue in the workflows that the tests are not run for updated requirements?

**Review by cqc-alec — APPROVED** [review]

**Comment by cqc-alec** [comment]
> @cqc-alec this looks like a issue in the workflows that the tests are not run for updated requirements?

Indeed, they should check for updated requirements too.

**Comment by cqc-melf** [comment]
Yes I have run that, so I think it is fine to merge this as it is.

**Comment by cqc-melf** [comment]
Should make a task for fixing that.

**Pull request merged**
